<a href="https://colab.research.google.com/github/junsoo321/hw/blob/main/1-10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
a=np.random.random((4,4))
print_val(a)

a=np.random.randn(4,4)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[0.34487986 0.81805125 0.58419348 0.84042671]
 [0.33197776 0.96457217 0.75332326 0.88434014]
 [0.9368771  0.34167505 0.35517023 0.76485663]
 [0.95085911 0.24437206 0.99811419 0.28696267]]
 
Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[ 1.23219155  0.48731092 -1.4638028   0.78781957]
 [-1.52909009 -0.16875762  0.17872822 -1.66434052]
 [ 0.3503751  -2.09064084 -0.41238263 -0.61532895]
 [ 1.02692847  0.55230206 -0.24894531 -0.50870473]]
 
