<a href="https://colab.research.google.com/github/junsoo321/hw/blob/main/1-11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print_val(a)

b=a[:2,1:3]
print_val(b)

row1=a[1,:]
print_val(row1)

Type: <class 'numpy.ndarray'>
Shape: (3, 4)
값:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[2 3]
 [6 7]]
 
Type: <class 'numpy.ndarray'>
Shape: (4,)
값:
 [5 6 7 8]
 
