<a href="https://colab.research.google.com/github/junsoo321/hw/blob/main/1-14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
print_val(m1/m2)
print_val(np.divide(m1,m2))

print_val(np.sqrt(m1))

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
 
