<a href="https://colab.research.google.com/github/junsoo321/hw/blob/main/1-21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
def print_val(x):
  print("Type:",type(x))
  print("Shape",x.shape)
  print("값:\n",x)
  print(" ")
m2=np.array([[5,6],[7,8]])
v1=np.array([9,10])
v2=np.array([11,12])


m1=np.array([[1,2,3],[4,5,6]])
print (m1)
print (m1.shape)
print("\n")
print_val(np.sum(m1))
print_val(np.sum(m1,axis=0))
print_val(np.sum(m1,axis=1))

[[1 2 3]
 [4 5 6]]
(2, 3)


Type: <class 'numpy.int64'>
Shape ()
값:
 21
 
Type: <class 'numpy.ndarray'>
Shape (3,)
값:
 [5 7 9]
 
Type: <class 'numpy.ndarray'>
Shape (2,)
값:
 [ 6 15]
 
