<a href="https://colab.research.google.com/github/junsoo321/hw/blob/main/1-22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
def print_val(x):
  print("Type:",type(x))
  print("Shape",x.shape)
  print("값:\n",x)
  print(" ")
v1=np.array([9,10])
v2=np.array([11,12])


m1=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
             [10,11,12]])
m2=np.zeros_like(m1)
print_val(m1)
print_val(m2)

Type: <class 'numpy.ndarray'>
Shape (4, 3)
값:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
 
Type: <class 'numpy.ndarray'>
Shape (4, 3)
값:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
 
